### ISSUE TITLE
Orion V2 tracking issue

### ISSUE THREAD

**Issue by Lezek123** [Joystream/orion#52]
**Mappings:**
- [x] Storage & Distribution
- [x] Memberships
- [x] Channels
- [x] Videos
- [x] Comments and reactions
- [x] Video nfts
- [x] Channel payouts _(https://github.com/Joystream/joystream/pull/4334,  **estimate**: TBD)_
- [x] Direct channel payouts (https://github.com/Joystream/joystream/pull/4517, **estimate:** 2h)

**Misc:**
- [x] https://github.com/Joystream/orion/issues/54
- [x] Deployment of Orion v2 to Subsquid Aquarium (this would allow easy, "one-click" deployment for anyone w/ a GitHub account, making it very useful for future gateway operators. _**Estimate:** ~2-4h left_)
- Issue w/ `OR` queries: https://github.com/subsquid/squid-sdk/issues/153

**User mutations:**
- [x] Video views
- [x] Channel follows
- [x] Channel/video reporting

**Operator mutations:**
- [x] Kill switch _(**Estimate:** < 1h)_
- [x] Video hero _(**Estimate:** 2h)_
- [x] Category featured videos _(**Estimate:** 2h)_
- [x] Supported categories
- [x] Content censoring on the Gateway level (https://github.com/Joystream/orion/issues/55) _(**Estimate:** 3h)_ 

**Queries:**
- [x] Filtering through views
- [x] `extendedChannels` (channels + activeVideosCount)
- [x] `mostRecentChannels`  _(**Estimate:** 3h)_
- [x] `channelNftCollectors` _(**Estimate:** 3h)_
- [x] `extendedVideoCategories` (category + activeVideosCount)  _(**Estimate:** 3h)_
- [x] `mostViewedVideosConnection`

**Operator queries:** _(**Estimate:** ~1-2 days, low priority)_
- [x] Video views
- [x] Channel/video follows
- [x] Channel/video reports

**Subscriptions:**
- [x] State subscription

**Documentation:**
- [x] Initial `CHANGELOG.md` (Orion v1 vs Orion v2)
- [x] Developer guide
- [ ] Operator guide _(**Estimate:** 4h)_

**Tests & benchmarks:**
- [ ] https://github.com/Joystream/orion/issues/65 _(**Estimate:** 4-5 days)_
